language: go

go:
  - 1.7
  - tip

install:
  - go get -d -v -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
  # - go get github.com/mattn/goveralls
  - git clone -b multiple-packages https://github.com/mattn/goveralls /tmp/goveralls
  - cd /tmp/goveralls
  - go install
  - cd -

script:
  - go test -v -race ./...
  - goveralls -service=travis-ci
  - go vet ./...
  - golint -set_exit_status .
